### ISSUE TITLE
在Firefox里的height问题

### ISSUE THREAD

**Issue by kongxiangyiren** [simon5057/xlsx-preview#3]
在Firefox里表格高度没有100%，请修改一下src\CSSStyles\base.ts 第35行
.${EXCEL_SHEETS_CLS} { position: relative; } 改成 .${EXCEL_SHEETS_CLS} { height:100%; position: relative; }

**Comment by simon5057** [comment]
I'll fix it soon, Thank you for your use and feedback! Have a good day.

**Comment by kongxiangyiren** [comment]
然后请问，您在安卓上试过吗，我的不知道为什么无法显示
